"""add_acked_columns_to_jobs

Revision ID: bbc0d80cc9f1
Revises: d6facbd4fc3c
Create Date: 2026-01-21 22:42:31.809466

AIDEV-NOTE: Adds acknowledgement tracking to jobs table.
- acked: Boolean flag to track if errors have been acknowledged
- acked_at: Timestamp when the acknowledgement occurred
- Adds indexes for efficient health queries filtering by acked status
- Safe migration: adds columns with defaults, no data loss risk
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbc0d80cc9f1"
down_revision: str | Sequence[str] | None = "d6facbd4fc3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        # AIDEV-NOTE: Use sa.false() for portable boolean default across databases
        batch_op.add_column(
            sa.Column("acked", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(sa.Column("acked_at", sa.DateTime(), nullable=True))
        batch_op.create_index("ix_jobs_acked", ["acked"], unique=False)
        batch_op.create_index("ix_jobs_status_acked", ["status", "acked"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_acked")
        batch_op.drop_index("ix_jobs_acked")
        batch_op.drop_column("acked_at")
        batch_op.drop_column("acked")

    # ### end Alembic commands ###
